#!/bin/bash

. ~/plescripts/plelib.sh
EXEC_CMD_ACTION=EXEC

typeset	-r	vm_name=kdeneon
typeset -r	vm_path="/home/kangs/VirtualBox VMs"

line_separator
info "Create VM $vm_name"
exec_cmd VBoxManage createvm --name $vm_name --basefolder \"$vm_path\" --register
LN

line_separator
info "Global config"
exec_cmd VBoxManage modifyvm $vm_name --ostype Ubuntu_64
exec_cmd VBoxManage modifyvm $vm_name --acpi on
exec_cmd VBoxManage modifyvm $vm_name --ioapic on
exec_cmd VBoxManage modifyvm $vm_name --memory 2048
exec_cmd VBoxManage modifyvm $vm_name --vram 12
exec_cmd VBoxManage modifyvm $vm_name --cpus 2
exec_cmd VBoxManage modifyvm $vm_name --rtcuseutc on
exec_cmd VBoxManage modifyvm $vm_name --largepages on
LN

line_separator
info "Add Iface 1"
exec_cmd VBoxManage modifyvm $vm_name --nic1 hostonly
exec_cmd VBoxManage modifyvm $vm_name --hostonlyadapter1 vboxnet1
exec_cmd VBoxManage modifyvm $vm_name --nictype1 virtio
exec_cmd VBoxManage modifyvm $vm_name --cableconnected1 on
LN

line_separator
info "Crée et attache le disque où sera installé l'OS."
exec_cmd VBoxManage createhd --filename \"$vm_path/$vm_name/$vm_name.vdi\" --size 32768
exec_cmd VBoxManage storagectl $vm_name --name SATA --add SATA --controller IntelAhci --portcount 1
exec_cmd VBoxManage storageattach $vm_name --storagectl SATA --port 0 --device 0 --type hdd --medium \"$vm_path/$vm_name/$vm_name.vdi\"
LN

line_separator
info "Ajoute $vm_name au groupe 'Desktop démo'"
exec_cmd VBoxManage modifyvm "$vm_name" --groups \"/Desktop démo\"
LN

#line_separator
#info "Démarrage de la VM $vm_name, l'installation va commencer..."
#exec_cmd VBoxManage startvm  $vm_name
#LN

