#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r str_usage=\
"Usage : $ME ...."

script_banner $ME $*

while [ $# -ne 0 ]
do
	case $1 in
		-emul)
			EXEC_CMD_ACTION=NOP
			first_args=-emul
			shift
			;;

		-h|-help|help)
			info "$str_usage"
			LN
			exit 1
			;;

		*)
			break
	esac
done

typeset	-a	alias_tns_list

#	Charge dans alias_tns_list le nom des bases 'physical' et la primary.
function load_alias_tns
{
	info "Load all tns"
	typeset -i	idb=0
	while read db_name dash type rem
	do
		[ x"$db_name" == x ] && continue

		alias_tns_list[$idb]=$db_name
		idb=idb+1
	done<<<"$(dgmgrl -silent sys/$oracle_password 'show configuration' |\
				grep -E "Primary|Physical")"
	info "$idb tns loaded."
	LN
}

#	$1 alias tns
function get_server_for
{
	tnsping $1 | tail -2 | head -1 | sed "s/.*HOST = \(.*\)) (PORT.*/\1/"
}

load_alias_tns

for tns in ${alias_tns_list[*]}
do
	server=$(get_server_for $tns)
	info "server = $server for $tns"
	if [ "$(hostname -s)" == "$server" ]
	then
		exec_cmd "$@"
	else
		exec_cmd "ssh $USER@$server \". .profile; $@\""
	fi
	LN
done
