#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/cfglib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r PARAMS="$*"
typeset -r str_usage=\
"Usage : $ME [-db=id]	(or use ID_DB)

Must be executed from the host server : show grid logs"

typeset db=undef

while [ $# -ne 0 ]
do
	case $1 in
		-emul)
			EXEC_CMD_ACTION=NOP
			first_args=-emul
			shift
			;;

		-db=*)
			db=${1##*=}
			shift
			;;

		-h|-help|help)
			info "$str_usage"
			LN
			exit 1
			;;

		*)
			error "Arg '$1' invalid."
			LN
			info "$str_usage"
			exit 1
			;;
	esac
done

[[ $db = undef ]] && [[ -v ID_DB ]] && db=$ID_DB
exit_if_param_undef db	"$str_usage"

cfg_exists $db

typeset -r	max_nodes=$(cfg_max_nodes $db)

[ $max_nodes -gt 2 ] && error "Maximum RAC 2 nœuds" && exit 1

cfg_load_node_info $db 1
typeset -r	node1=$cfg_server_name

set_terminal_title "GRID LOGS"

if [ $max_nodes -eq 2 ]
then	#	RAC 2 nœuds
	cfg_load_node_info $db 2
	typeset -r	node2=$cfg_server_name

	typeset -r	session_name="GI Left $node1 / Right $node2"
	exec_cmd -ci tmux kill-session -t \"$session_name\"

	tmux new -s "$session_name"		\
		"ssh root@${node1} '. .bash_profile; tail -1000f \$GRID_BASE/diag/crs/$node1/crs/trace/alert.log'"	\;\
		split-window -h				\
		"ssh root@${node2} '. .bash_profile; tail -1000f \$GRID_BASE/diag/crs/$node2/crs/trace/alert.log'"	\;\
		split-window -v				\
		"ssh -t root@${node2} '. .bash_profile; tail -1000f \$GRID_BASE/diag/asm/+asm/+ASM2/trace/alert_+ASM2.log'"	\;\
		selectp -t 0 																								\;\
		split-window -v				\
		"ssh -t root@${node1} '. .bash_profile; tail -1000f \$GRID_BASE/diag/asm/+asm/+ASM1/trace/alert_+ASM1.log'"

else	#	Mono instance
	typeset -r	session_name="GI $node1"
	exec_cmd -ci tmux kill-session -t \"$session_name\"

	tmux new -s "$session_name"	\
	"ssh root@${node1} '. .bash_profile; tail -1000f \$GRID_BASE/diag/crs/$node1/crs/trace/alert.log'"	\;\
	split-window -v				\
	"ssh -t root@${node1} '. .bash_profile; tail -1000f \$GRID_BASE/diag/asm/+asm/+ASM/trace/alert_+ASM.log'"
fi

set_terminal_title default
