#!/bin/bash

# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r str_usage=\
"Usage : $ME ...."

info "$ME $@"

typeset db=undef

while [ $# -ne 0 ]
do
	case $1 in
		-emul)
			EXEC_CMD_ACTION=NOP
			first_args=-emul
			shift
			;;

		-db=*)
			db=${1##*=}
			shift
			;;

		-h|-help|help)
			info "$str_usage"
			LN
			exit 1
			;;

		*)
			error "Arg '$1' invalid."
			LN
			info "$str_usage"
			exit 1
			;;
	esac
done

[[ $db = undef ]] && [[ -v ID_DB ]] && db=$ID_DB
exit_if_param_undef db	"$str_usage"

typeset -r	cfg_path=~/plescripts/database_servers/$db
typeset -r	max_nodes=$(ls -1 $cfg_path/node* | wc -l)

[ $max_nodes -gt 2 ] && error "Maximum RAC 2 nœuds" && exit 1

typeset -r	node1=$(cat $cfg_path/node1 | cut -d: -f2)
if [ $max_nodes -eq 2 ]
then	#	RAC 2 nœuds
	typeset -r	node2=$(cat $cfg_path/node2 | cut -d: -f2)

	typeset -r	session_name="GI Left $node1 / Right $node2"
	exec_cmd -ci tmux kill-session -t \"$session_name\"

	tmux new -s "$session_name"	"ssh root@${node1} tail -1000f /u01/app/grid/diag/crs/$node1/crs/trace/alert.log"							\;\
								split-window -h "ssh root@${node2} tail -1000f /u01/app/grid/diag/crs/$node2/crs/trace/alert.log"			\;\
								split-window -v "ssh -t root@${node2} tail -1000f /u01/app/grid/diag/asm/+asm/+ASM2/trace/alert_+ASM2.log"	\;\
								selectp -t 0 																								\;\
								split-window -v "ssh -t root@${node1} tail -1000f /u01/app/grid/diag/asm/+asm/+ASM1/trace/alert_+ASM1.log"
else	#	Mono instance
	typeset -r	session_name="GI $node1"
	exec_cmd -ci tmux kill-session -t \"$session_name\"

	tmux new -s "$session_name"	"ssh root@${node1} tail -1000f /u01/app/grid/diag/crs/$node1/crs/trace/alert.log"							\;\
								split-window -v "ssh -t root@${node1} tail -1000f /u01/app/grid/diag/asm/+asm/+ASM/trace/alert_+ASM.log"
fi
