#!/bin/bash

# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r str_usage=\
"Usage : $ME ...."

info "$ME $@"

typeset -r account=$1

if [[ -v ID_DB ]]
then
	db=$ID_DB
else
	error "use set_db before !"
	exit 1
fi

typeset -r cfg_path=~/plescripts/database_servers
exit_if_dir_not_exists $cfg_path

typeset -ri max_nodes=$(ls -1 $cfg_path/$db/node*|wc -l)

if [ $max_nodes -gt 1 ]
then
	typeset -a node_list

	for i in $( seq 0 $max_nodes )
	do
		node_list[$i]=$(printf "srv%s%02d" $db $((i+1)))
	done

	wait_server

	tmux new -s "$db@${account}" "ssh -t ${account}@${node_list[0]}" \; \
			split-window -h "ssh -t ${account}@${node_list[1]}"  \; \
			selectp -t 0 
else
	info "TODO"
fi
