#!/bin/bash

#	ts=4 sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/networklib.sh
EXEC_CMD_ACTION=EXEC

. ~/plescripts/global.cfg

typeset -r ME=$0

typeset -r str_usage=\
"Usage : $ME
	[-db=<str>]            Préciser la base sinon s'appuie sur set_db
	[-wait_time_secs=<#>]  Temps de pause entre chaque tentative.
	[-node=<#>]            N° du nœud à attendre.
"

typeset		db=undef
typeset	-i	nr_node=1
typeset	-i	wait_time_secs=10

while [ $# -ne 0 ]
do
	case $1 in
		-db=*)
			db=${1##*=}
			shift
			;;

		-wait_time_secs=*)
			wait_time_secs=${1##*=}
			shift
			;;

		-node=*)
			nr_node=${1##*=}
			shift
			;;

		*)
			error "Arg '$1' invalid."
			LN
			info $str_usage
			exit 1
			;;
	esac
done

[[ $db = undef ]] && [[ -v ID_DB ]] && db=$ID_DB
exit_if_param_undef db

typeset -r node=$(printf "srv%s%02d" ${db} $nr_node)
wait_server $node
[ $? -ne 0 ] && exit 1

start_s=$SECONDS
while [ 0 -eq 0 ]
do
	exec_cmd -c "ssh grid@$node \". ~/.profile; crsctl stat res -t\""
	[ $? -eq 0 ] && exit 0
	info -n "Waiting : "; pause_in_secs $wait_time_secs
	duration=$(( $SECONDS - $start_s ))
	info -f ", ${YELLOW}Total wait $(fmt_seconds $duration)${NORM}..."
	LN
done
