#!/bin/sh

#	ts=4	sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r str_usage=\
"Usage : $ME ...."

info "$ME $@"

typeset -r db=$1
typeset -r patternServer=srv${db}0[1-9]

function virtualbox_start
{
	typeset -a vm_list
	typeset -i ivm=0
	while read vm_name
	do
		vm_list[$ivm]=$vm_name
		ivm=ivm+1
	done<<<"$(VBoxManage list vms | grep "$patternServer" | cut -d\" -f2)"

	typeset -ri max_vms=${#vm_list[@]}

	[ $max_vms -eq 0 ] && error "Server for $db not found." && exit 1

	exec_cmd -c "VBoxManage startvm ${vm_list[0]} --type headless"
	[ $? -ne 0 ] && error "Failed to start ${vm_list[0]}"
	LN

	for ivm in $( seq 1 $(( max_vms - 1 )) )
	do
		wait_server ${vm_list[$((ivm-1))]}
		LN

		exec_cmd "VBoxManage startvm ${vm_list[$ivm]} --type headless"
		[ $? -ne 0 ] && error "Failed to start ${vm_list[$ivm]}"
		LN
	done
}

case ${hostvm##*_} in
	virtualbox)
		virtualbox_start
		;;

	*)
		error "${hostvm##*_} not implemented."
		exit 1
		;;
esac

