#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/networklib.sh
. ~/plescripts/cfglib.sh

typeset -r nc_installed=$(which nc)
[ x"$nc_installed" = x ] && error "La commande nc n'est pas présente, installer le package netcat-openbsd ou nmap-ncat" && exit 1

typeset -ri max_time=180	#seconds

function ping_server
{
	typeset -r server_name=$1

	typeset -i	count_pings=0

	hide_cursor

	info -n "Wait network interface up :  "
	start=$SECONDS
	duration=0
	car="|"
	while [ $duration -lt $max_time ]
	do
		printf "\b\b\b[$car]"
		if ! ping_test $server_name
		then
			case $car in
				"|")	car="/"
					;;
				"/")	car="-"
					;;
				"-")	car="\\"
					;;
				"\\")	car="|"
					;;
			esac
			duration=$(( $SECONDS - $start ))
		else
			break
		fi
	done
	printf "\b\b\b\b "

	if [ $duration -ge $max_time ]
	then
		printf "[$KO] Waiting : %s\n" $(fmt_seconds $duration)
		show_cursor
		return 1
	else
		printf "[$OK] Waiting %s\n" $(fmt_seconds $duration)
		return 0
	fi
}

function wait_for
{
	typeset -r server_name=$1

	info "Wait $server_name max time $(fmt_seconds $(( $max_time * 2 )) ) :"

	if ! ping_server $server_name
	then
		return 1
	fi

	start=$SECONDS
	info -n "Wait sshd up : "
	duration=0
	while [ $duration -lt $max_time ]
	do
		if ! port_open $server_name 22
		then
			pause_in_secs 5 "$suffix"
			typeset -i l=$?
			b=$(fill "\b" $l)
			printf "$b"
			suffix=" (Total : $(fmt_seconds $(( $SECONDS - $start ))))"
			duration=$(( $SECONDS - $start ))
		else
			break
		fi
	done

	show_cursor

	if [ $duration -ge $max_time ]
	then
		printf "[$KO] Waiting %s${CEOL}\n" $(fmt_seconds $duration)
		return 1
	else
		printf "[$OK] Waiting %s${CEOL}\n"  $(fmt_seconds $duration)
		return 0
	fi
}


if [ $# -eq 0 ]
then
	if [[ -v ID_DB ]]
	then
		typeset -i	exit_code=0
		cfg_exists $ID_DB
		typeset	-ri max_nodes=$(cfg_max_nodes $ID_DB)
		for (( i=1; i <= max_nodes; ++i ))
		do
			cfg_load_node_info $ID_DB $i
			if ! wait_for $cfg_server_name
			then
				exit_code=1
			fi
			LN
		done
		exit $exit_code
	else
		error "Missing server name"
		exit 1
	fi
fi

wait_for $1
exit $?
