#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/cfglib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r account=$1

if [[ -v ID_DB ]]
then
	db=$ID_DB
else
	error "use set_db before !"
	exit 1
fi

cfg_exists $db use_return_code
if [[ $? -eq 1 ]]
then
	warning "Try connection to : $db"
	wait_server ${db}
	[ $? -eq 0 ] && exec_cmd -ci ssh -Y $account@${db} || true
	exit $?
fi

typeset -ri max_nodes=$(cfg_max_nodes $db)

typeset -i node=1
[ $# -eq 2 ] && node=$2

[ $max_nodes -gt 1 ] && type=RAC || type=single
info "$type node."

typeset -r server_name=$(printf "srv%s%02d" $db $node)

wait_server ${server_name}
if [ $? -eq 0 ]
then
	set_terminal_title "$account@${server_name}"
	exec_cmd -ci ssh -Y $account@${server_name}
	set_terminal_title default
else
	exit 1
fi
