#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/cfglib.sh
. ~/plescripts/vmlib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r account=$1

if [[ -v ID_DB ]]
then
	db=$ID_DB
else
	error "use set_db before !"
	exit 1
fi

if ! cfg_exists $db use_return_code
then
	info -n "VM $db running : "
	if ! vm_running $db
	then
		info -f "[$KO]"
		LN
		error "No identifier or VM $db"
		LN
		exit 1
	fi
	info -f "[$OK]"
	LN
	info "Connection to server : $db"
	wait_server ${db}
	set_terminal_title "$account@${db}"
	[ $? -eq 0 ] && exec_cmd -ci ssh -Y $account@${db} || true
	ret=$?
	set_terminal_title default
	exit $ret
fi

typeset -ri max_nodes=$(cfg_max_nodes $db)

typeset -i node=1
[ $# -eq 2 ] && node=$2 || true

cfg_load_node_info $db $node

if [ $cfg_db_type == rac ]
then
	type=RAC
elif [ $cfg_dataguard == yes ]
then
	type=Dataguard
else
	type=single
fi
info "$type node."

typeset -r server_name=$(printf "srv%s%02d" $db $node)

info -n "VM $server_name running : "
if ! vm_running $server_name
then
	info -f "[$KO]"
	LN
	exit 1
else
	info -f "[OK]"
	LN
fi

wait_server ${server_name}
if [ $? -eq 0 ]
then
	set_terminal_title "$account@${server_name}"
	exec_cmd -ci ssh -Y $account@${server_name}
	ret=$?
	set_terminal_title default
	exit $ret
else
	exit 1
fi
