#!/bin/sh

function make_vimrc_file # $1 full_path_vimrc
{
	typeset -r full_path_vimrc=$1

	cp ~/plescripts/myconfig/myvimrc $full_path_vimrc
	cp ~/plescripts/myconfig/.vimtips ${full_path_vimrc%/*}/.vimtips
}
