#!/bin/bash
# vim: ts=4:sw=4

#	Le script plescripts/db/dbfs/mount-dbfs est copié dans $ORACLE_HOME/ et
#	renommé en mount-dbfs-"nom du point de montage"

#	Le script contient le nom du point de montage.
typeset -r mount_point_name="${0##*-}"

typeset	-r log_name=/tmp/log-dbfs-${mount_point_name}_$(date +%d).log

#	L'agent trace le script dans le fichier crsd_scriptagent_grid.trc
#	répertoire : /u01/app/grid/diag/crs/$(hostname -s)/crs/trace

function mount_dbfs
{
	echo sudo -iu oracle mount /mnt/$mount_point_name
	sudo -iu oracle mount /mnt/$mount_point_name
}

function umount_dbfs
{
	echo sudo -iu oracle fusermount -u /mnt/$mount_point_name
	sudo -iu oracle fusermount -u /mnt/$mount_point_name
}

function check_mount_point
{
	echo sudo -iu oracle test -d /mnt/$mount_point_name/staging_area
	sudo -iu oracle test -d /mnt/$mount_point_name/staging_area
}

function force_umount
{
	echo "Force umount"
	echo sudo -iu oracle fusermount -u -z /mnt/$mount_point_name
	sudo -iu oracle fusermount -u /mnt/$mount_point_name
	sudo -iu oracle fusermount -u -z /mnt/$mount_point_name
}

echo >> $log_name
echo "run at $(date +"%Y/%m/%d %Hh%M")" >> $log_name
echo "args = '$@'" >> $log_name
case "$1" in
	start)
		mount_dbfs >> $log_name 2>&1
		;;

	stop|delete)
		umount_dbfs >> $log_name 2>&1
		;;

	check)
		check_mount_point >> $log_name 2>&1
		;;

	clean)
		force_umount >> $log_name 2>&1
		;;

	*)
		echo "'$1' ignored" >> $log_name 2>&1
		exit 1
		;;
esac

ret=$?
echo "Arg '$1' : return code = $ret" >> $log_name
exit $ret
