#!/bin/bash

#	ts=4	sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r str_usage=\
"Usage : $ME <str>"

info "$ME $@"

[[ $# -eq 0 ]] && [[ -v ID_DB ]] && server=$ID_DB || server=$1

if [ x"$server" == x ]
then
	error "$str_usage"
	exit 1
fi

#typeset -r vm_metrics="Net/Rate/Rx,Net/Rate/Tx,CPU/Load/User,CPU/Load/Kernel,RAM/Usage/Used,Disk/Usage/Used"
typeset -r vm_metrics="CPU/Load/User,CPU/Load/Kernel,Guest/CPU/Load/User,Guest/CPU/Load/Kernel"

function vb_metrics_for
{
	typeset -r vm_name="$1"

	exec_cmd "VBoxManage metrics collect --period 2		\
						${vm_name} \"$vm_metrics\"		\
					> /tmp/metrics_${vm_name}.txt &"

	echo -n " $!" >> /tmp/metrics_pid_list.txt
}

function virtualbox_metrics
{
	typeset -a vm_list
	typeset -i ivm=0
	while read vm_name
	do
		if [ x"$vm_name" != x ]
		then
			vm_list[$ivm]=$vm_name
			ivm=ivm+1
		fi
	done<<<"$(VBoxManage list vms | grep "$server" | cut -d\" -f2)"

	typeset -ri max_vms=${#vm_list[@]}

	info "$max_vms server(s) found for pattern $server : ${vm_list[@]}"
	[ $max_vms -eq 0 ] && exit 1

	rm -rf /tmp/metrics_pid_list.txt

	line_separator
	vb_metrics_for K2
	LN

	for i in $( seq $max_vms )
	do
		line_separator
		vb_metrics_for "${vm_list[i-1]}"
		LN
	done

	ask_for -reply_list=CR "Press enter to stop..."

	line_separator
	exec_cmd -c kill -1 $(cat /tmp/metrics_pid_list.txt)
	LN

	line_separator
	info "Wait until all childs stopped..."
	wait
	return 0
}

case ${hostvm##*_} in
	virtualbox)
		virtualbox_metrics
		exit $?
		;;

	*)
		error "${hostvm##*_} not implemented."
		exit 1
		;;
esac

