#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r PARAMS="$*"
typeset -r str_usage=\
"Usage : $ME ...."

typeset	db=undef

while [ $# -ne 0 ]
do
	case $1 in
		-emul)
			EXEC_CMD_ACTION=NOP
			shift
			;;

		-db=*)
			db=${1##*=}
			shift
			;;

		-h|-help|help)
			info "$str_usage"
			LN
			exit 1
			;;

		*)
			error "error"
			info "$str_usage"
			LN
			exit 1
			;;
	esac
done

[[ $db == undef && x"$ID_DB" ]] && db=$ID_DB
exit_if_param_undef db	"$str_usage"

show_info_server -db=$db | sed '1,2d' > /tmp/info.txt
clean_log_file /tmp/info.txt
cat /tmp/info.txt
rm -r /tmp/info.txt
