#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r PARAMS="$*"
typeset -r str_usage=\
"Usage : $ME <str>"

typeset server=undef
typeset error_on_poweroff=no

while [ $# -ne 0 ]
do
	case $1 in
		-emul)
			EXEC_CMD_ACTION=NOP
			shift
			;;

		-server=*)
			server=${1##*=}
			shift
			;;

		-error_on_poweroff)
			error_on_poweroff=yes
			shift
			;;

		-h|-help|help)
			info "$str_usage"
			LN
			exit 1
			;;

		*)
			if [ $server == undef ]
			then
				server=$1
				shift
			else
				error "Arg '$1' invalid."
				LN
				info "$str_usage"
				exit 1
			fi
			;;
	esac
done

[[ "$server" == undef && -v ID_DB ]] && server=$ID_DB || true

exit_if_param_undef server	"$str_usage"

typeset	-a	running_db_server_list

# Si dès VMs sont actives elles sont mémorisés dans running_db_server_list.
# return 0 si des VMs sont actives, 1 sinon.
function load_running_vms
{
	while read vm_name rem
	do
		[ x"$vm_name" == x ] && continue || true

		vm_name=$(cut -d\" -f2<<<"$vm_name")
		if [ ${vm_name:0:3} == "srv" ]
		then
			id=$(sed "s/srv\(.*\)..$/\1/"<<<"$vm_name")
			if ! grep -q $id <<<"${running_db_server_list[*]}"
			then
				running_db_server_list+=( $id )
			fi
		fi

	done<<<"$(VBoxManage list runningvms)"

	[ ${#running_db_server_list[@]} -eq 0 ] && return 1 || return 0
}

# $1 vm name
# return 0 if running, else 1
function vm_running
{
	grep -q "$1"<<<"$(VBoxManage list runningvms)"
}

if ! vm_running $server
then
	error "VM $server not running."
	LN
	exit 1
fi

if [ "$server" == "$infra_hostname" ]
then # On doit arrêter les serveurs de BDD pour arrêter le serveur d'infra.
	if load_running_vms
	then
		info "DB servers running : ${running_db_server_list[*]}"
		confirm_or_exit "Stop them"

		for vm in ${running_db_server_list[*]}
		do
			exec_cmd stop_vm -server=$vm -dataguard=no
		done
		LN
	fi
fi

case $error_on_poweroff in
	no)
		exec_cmd stop_vm -server=$server -dataguard=no
		LN
		;;
	yes)
		exec_cmd stop_vm -server=$server -error_on_poweroff -dataguard=no
		LN
		;;
esac

exec_cmd "start_vm $server -wait_os=no -dataguard=no"
LN

if [ ${#running_db_server_list[@]} -ne 0 ]
then
	for vm in ${running_db_server_list[*]}
	do
		exec_cmd start_vm -server=$vm -wait_os=no -dataguard=no
	done
	LN
fi
