#!/bin/bash
# vim: ts=4:sw=4

. ~/plescripts/plelib.sh
. ~/plescripts/global.cfg
EXEC_CMD_ACTION=EXEC

typeset -r ME=$0
typeset -r str_usage=\
"Usage : $ME <str>"

script_banner $ME $@

[[ $# -eq 0 ]] && [[ -v ID_DB ]] && server=$ID_DB || server=$1

if [ x"$server" == x ]
then
	error "$str_usage"
	exit 1
fi

typeset -a vm_list
while read vm_name
do
	[ x"$vm_name" != x ] && vm_list+=( $vm_name )
done<<<"$(VBoxManage list vms | grep "$server" | cut -d\" -f2)"

typeset -ri max_vms=${#vm_list[@]}

[ $max_vms -eq 0 ] && error "Server for $server not found." && exit 1

for vm in ${vm_list[*]}
do
	exec_cmd -c "VBoxManage controlvm $vm savestate"
	[ $? -ne 0 ] && error "Failed to save $vm"
	LN
done
